from .soil_tests import SoilTests
from .water_tests import WaterTests
from .zone_tests import ZoneTests
from .planttype_tests import PlantTypeTests
from .crittertype_tests import CritterTypeTests
from .light_tests import LightTests
from .veggiecat_tests import VeggieCatTests
from .plantzonepairing_tests import PlantZonePairingTests
from .plantcritterpairing_tests import PlantCritterPairingTests
from .companionpairing_tests import CompanionPairingTests
from .favorite_tests import FavoriteTests
from .critter_tests import CritterTests
from .plant_tests import PlantTests