# Generated by Django 5.0 on 2023-12-06 17:23

import django.core.validators
import gardenapi.models.critter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0002_plant_block_size_alter_plant_icon_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='icon_url',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='critter',
            name='image_url',
        ),
        migrations.AddField(
            model_name='critter',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), gardenapi.models.critter.validate_square_image]),
        ),
    ]
