# Generated by Django 5.0 on 2023-12-07 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0004_remove_light_hours_light_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='block_size',
        ),
    ]
