# Generated by Django 5.0 on 2023-12-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0005_remove_plant_block_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soil',
            old_name='type',
            new_name='soil_type',
        ),
    ]
