# Generated by Django 5.0 on 2023-12-15 17:37

import django.core.validators
import django.db.models.deletion
import gardenapi.models.critter
import gardenapi.models.plant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0006_rename_type_soil_soil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critter',
            name='image',
            field=models.ImageField(null=True, upload_to='images/critters', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='icon',
            field=models.ImageField(null=True, upload_to='images/icons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(null=True, upload_to='images/plants', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'avif'])]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='veggie_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veggies_in_this_category', to='gardenapi.veggiecat'),
        ),
    ]
