# Generated by Django 5.0 on 2023-12-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0007_alter_critter_image_alter_plant_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='critter',
            name='insect',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='annual',
            field=models.BooleanField(default=True),
        ),
    ]
