# Generated by Django 5.0 on 2023-12-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenapi', '0009_alter_plant_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='days_to_mature',
        ),
        migrations.AddField(
            model_name='plant',
            name='maturity',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
